version: '3.9'
services:
  db:
    image: mysql:8.0.21
    container_name: delivery-app-db
    ports:
      - 3306:3306
    volumes:
      - ./back-end/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE

# version: '3.9'
# services:
#   backend:
#     container_name: delivery-app
#     ports:
#       - 3001:3001
#     working_dir: /back-end
#     depends_on:
#       db:
#         condition: service_healthy
#     environment:
#       - NODE_ENV=development
#       - MYSQL_HOST=localhost
#       - API_PORT=3001
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=password
#       - MYSQL_DB_NAME=delivery-app
#       - MYSQL_PORT=3306
#       - DB_HOST=db
#       - PORT=3001
#     healthcheck:
#       test: ["CMD", "lsof", "-t", "-i:3001"]
#       interval: 1m30s
#       timeout: 10s
#       retries: 5
#       start_period: 40s
#   db:
#     image: mysql:8.0.21
#     container_name: delivery-app-db
#     ports:
#       - 3002:3306
#     environment:
#       - MYSQL_PASSWORD=password
#     restart: always
#     healthcheck:
#       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#       timeout: 10s
#       retries: 5
#     cap_add:
#       - SYS_NICE
